version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.3-node
        environment:
          DATABASE_URL: postgres://root@localhost:5432/arlo-test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: arlo-test
    steps:
      - checkout
      - run:
          name: install
          command: |
            make install install-development
      - run:
          name: create data model
          command: |
            make resetdb
      - run:
          name: type check
          command: |
            make typecheck
      - run:
          name: backend tests
          command: |
            make test-server
      - run:
          name: frontend tests
          command: |
            make test-client

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
